<a href="https://colab.research.google.com/github/ramabharti8/Tommorrow_RainPrediction/blob/main/RainPrediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Importing libraries

In [ ]:
import numpy as np
import pandas as pd  

##Importing Dataset

In [ ]:
dataset = pd.read_csv('weatherAUS.csv')
X = dataset.iloc[:,[1,2,3,4,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21]].values
Y = dataset.iloc[:,-1].values

In [ ]:
print(X)

[['Albury' 13.4 22.9 ... 16.9 21.8 'No']
 ['Albury' 7.4 25.1 ... 17.2 24.3 'No']
 ['Albury' 12.9 25.7 ... 21.0 23.2 'No']
 ...
 ['Wollongong' 17.4 22.3 ... 18.7 20.2 'No']
 ['Wollongong' 17.9 28.8 ... 22.3 26.5 'No']
 [nan nan nan ... nan nan nan]]


In [ ]:
print(Y)

['No' 'No' 'No' ... 'No' 'No' nan]


In [ ]:
Y = Y.reshape(-1,1)

##Dealing with invalid Data

In [ ]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan,strategy='most_frequent')
X = imputer.fit_transform(X)
Y = imputer.fit_transform(Y)

In [ ]:
print(X)

[['Albury' 13.4 22.9 ... 16.9 21.8 'No']
 ['Albury' 7.4 25.1 ... 17.2 24.3 'No']
 ['Albury' 12.9 25.7 ... 21.0 23.2 'No']
 ...
 ['Wollongong' 17.4 22.3 ... 18.7 20.2 'No']
 ['Wollongong' 17.9 28.8 ... 22.3 26.5 'No']
 ['Sydney' 17.0 25.0 ... 20.6 18.4 'No']]


In [ ]:
print(Y)

[['No']
 ['No']
 ['No']
 ...
 ['No']
 ['No']
 ['No']]


##Encoding Dataset

In [ ]:
from sklearn.preprocessing import LabelEncoder
le1 = LabelEncoder()
X[:,0] = le1.fit_transform(X[:,0])
le2 = LabelEncoder()
X[:,4] = le2.fit_transform(X[:,4])
le3 = LabelEncoder()
X[:,6] = le3.fit_transform(X[:,6])
le4 = LabelEncoder()
X[:,7] = le4.fit_transform(X[:,7])
le5 = LabelEncoder()
X[:,-1] = le5.fit_transform(X[:,-1])
le6 = LabelEncoder()
Y[:,-1] = le6.fit_transform(Y[:,-1])

In [ ]:
print(X)

[[0 13.4 22.9 ... 16.9 21.8 0]
 [0 7.4 25.1 ... 17.2 24.3 0]
 [0 12.9 25.7 ... 21.0 23.2 0]
 ...
 [14 17.4 22.3 ... 18.7 20.2 0]
 [14 17.9 28.8 ... 22.3 26.5 0]
 [10 17.0 25.0 ... 20.6 18.4 0]]


In [ ]:
print(Y)

[[0]
 [0]
 [0]
 ...
 [0]
 [0]
 [0]]


In [ ]:
Y = np.array(Y,dtype=float)
print(Y)

[[0.]
 [0.]
 [0.]
 ...
 [0.]
 [0.]
 [0.]]


##Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)

In [ ]:
print(X)

[[-1.6187526   0.03739718 -0.16062557 ... -0.15110851 -0.0826837
  -0.53038492]
 [-1.6187526  -0.99971247  0.20591174 ... -0.09534793  0.34685423
  -0.53038492]
 [-1.6187526  -0.04902862  0.30587646 ...  0.61095279  0.15785754
  -0.53038492]
 ...
 [ 1.78155691  0.72880361 -0.26059029 ...  0.18345499 -0.35758798
  -0.53038492]
 [ 1.78155691  0.81522942  0.82236086 ...  0.85258198  0.72484762
  -0.53038492]
 [ 0.81003991  0.65966297  0.18925096 ...  0.53660535 -0.66685529
  -0.53038492]]


##Splitting Dataset into Training set and Test set

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2,random_state=0)

In [ ]:
print(X_train)

[[ 0.08140215  0.60780749 -0.21060793 ...  0.61095279 -0.09986522
  -0.53038492]
 [-0.6472356  -2.55537694 -1.09362963 ... -2.3443581  -0.90739653
  -0.53038492]
 [ 1.05291916  0.93622554  0.52246669 ...  0.94551629 -0.01395763
   1.88542314]
 ...
 [ 0.08140215  0.48681136 -0.57714524 ...  0.10910754 -0.46067708
  -0.53038492]
 [ 1.78155691  1.23007328  0.48914512 ...  0.96410315  0.55303244
  -0.53038492]
 [-1.6187526  -0.82686086 -1.66009638 ... -1.52653622 -2.00701364
  -0.53038492]]


In [ ]:
print(Y_train)

[[0.]
 [0.]
 [1.]
 ...
 [0.]
 [0.]
 [1.]]


##Training Model

In [ ]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators=100,random_state=0)
classifier.fit(X_train,Y_train)

<ipython-input-21-84bb09ba651d>:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  classifier.fit(X_train,Y_train)


RandomForestClassifier(random_state=0)

In [ ]:
classifier.score(X_train,Y_train)

0.9997117823380217

In [ ]:
y_pred = le6.inverse_transform(np.array(classifier.predict(X_test),dtype=int))
Y_test = le6.inverse_transform(np.array(Y_test,dtype=int))

/usr/local/lib/python3.8/dist-packages/sklearn/preprocessing/_label.py:154: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [ ]:
print(y_pred)

['No' 'No' 'Yes' ... 'Yes' 'No' 'No']


In [ ]:
print(Y_test)

['No' 'No' 'Yes' ... 'Yes' 'No' 'No']


In [ ]:
y_pred = y_pred.reshape(-1,1)
Y_test = Y_test.reshape(-1,1)

In [ ]:
df = np.concatenate((Y_test,y_pred),axis=1)
dataframe = pd.DataFrame(df,columns=['Rain on Tommorrow','Predition of Rain'])

In [ ]:
print(dataframe)

     Rain on Tommorrow Predition of Rain
0                   No                No
1                   No                No
2                  Yes               Yes
3                   No                No
4                   No                No
...                ...               ...
8670                No                No
8671                No                No
8672               Yes               Yes
8673                No                No
8674                No                No

[8675 rows x 2 columns]


##Calculating Accuracy

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(Y_test,y_pred)

0.854178674351585

In [ ]:
dataframe.to_csv('prediction.csv')